export interface EuravibImport {
    id: number | null;
    suppl_Nr: string | null;
    dimset: string | null;
    entry_Date: string | null;
    rev_Date: string | null;
    cas_Nr: string | null;
    cas_Perc: string | null;
    h_Nr: string | null;
    h_Cat: string | null;
    adr_Un_Nr: string | null;
    adr_Cargo_Name: string | null;
    adr_TransportHazard_Class: string | null;
    adr_Packaging_Group: string | null;
    adr_Environment_Hazards: string | null;
    adr_ExtraInfo: string | null;
    imdg_Un_Nr: string | null;
    imdg_Cargo_Name: string | null;
    imdg_TransportHazard_Class: string | null;
    imdg_Packaging_Group: string | null;
    imdg_Environment_Hazards: string | null;
    imdg_ExtraInfo: string | null;
    extraInfo_TunnelCode: string | null;
    flashPoint: string | null;
    ems_Fire: string | null;
    ems_Spillage: string | null;
    user: string | null;
    eg_Nr: string | null;
}

